  q### Instructions:

- You can attempt any number of questions and in any order.  
  See the assignment page for a description of the hurdle requirement for this assessment.
- You may submit your practical for autograding as many times as you like to check on progress, however you will save time by checking and testing your own code before submitting.
- Develop and check your answers in the spaces provided.
- **Replace** the code `raise NotImplementedError()` with your solution to the question.
- Do **NOT** remove any variables other provided markings already provided in the answer spaces.
- Do **NOT** make any changes to this notebook outside of the spaces indicated.  
  (If you do this, the submission system might not accept your work)

### Submitting:

1. Before you turn this problem in, make sure everything runs as expected by resetting this notebook.    
   (You can do this from the menubar above by selecting `Kernel`&#8594;`Restart Kernel and Run All Cells...`)
1. Don't forget to save your notebook after this step.
1. Submit your .ipynb file to Gradescope via file upload or GitHub repository.
1. You can submit as many times as needed.
1. You **must** give your submitted file the **identical** filename to that which you downloaded without changing **any** aspects - spaces, underscores, capitalisation etc. If your operating system has changed the filename because you downloaded the file twice or more you **must** also fix this.  



---

# <mark style="background: #2dc26b; color: #ffffff;" >&nbsp;B3&nbsp;</mark>&ensp;Topic 8: Sorting (ii)

In [35]:
import numpy as np
from string import ascii_uppercase, ascii_lowercase
from random import shuffle

#### Question 01 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Write a function defined as:
```python
def lomuto_partition_pivot(arr, low, high):
```
that accepts a list to be sorted and the low and high range of indexes forming the partition to be conisdered for sorting and returns the quicksort pivot value using a Lomuto partition scheme or `None` for a zero length input array. The value of `high` is the actual list index considered.

For example:
```python
lomuto_partition_pivot([10, 9, 5, 2, 6, 4, 7, 1], 0, 7)
```
considers the whole list and returns the value `1` as the pivot value.

In [36]:
### 1. lomuto_partition_pivot
# Q: Implement Lomuto partitioning where the last element is the pivot.
# A: Rearrange elements around pivot such that smaller go left, larger go right.
def lomuto_partition_pivot(arr, low, high):
    pivot = arr[high]
    i = low - 1
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1


In [37]:
# Testing Cell (Do NOT modify this cell)

#### Question 02 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Write a function defined as:
```python
def median_of_three_pivot(arr, low, high):
```
that accepts a list to be sorted and the low and high indexes of the partition to be conisdered for sorting and returns the quicksort pivot value using a median partition scheme or `None` for a zero length input array.

For example:
```python
median_of_three_pivot([10, 9, 5, 2, 6, 4, 7], 0, 6)
```
considers the whole list and returns the value `7` being the middle value in `10`, `2` and `7`.

In [38]:

### 2. median_of_three_pivot
# Q: Choose the median of the first, middle, and last as pivot.
# A: Return index of the median value.
def median_of_three_pivot(arr, low, high):
    mid = (low + high) // 2
    a, b, c = arr[low], arr[mid], arr[high]
    if a <= b <= c or c <= b <= a:
        return mid
    elif b <= a <= c or c <= a <= b:
        return low
    else:
        return high


In [39]:
# Testing Cell (Do NOT modify this cell)

#### Question 03 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_quicksort(arr, reverse = False):
```
that uses a quicksort with median partition scheme to sort a list of floats in-place. The parameter `reverse` selects the direction of the sort order where `reverse == True` indicates a descending sort.

In [40]:
### 3. median_quicksort
# Q: Quicksort using median-of-three pivot.
# A: Partition based on median pivot and recurse.
def median_quicksort(arr, reverse=False):
    def quicksort_helper(arr, low, high):
        if low < high:
            pivot_index = median_of_three_pivot(arr, low, high)
            arr[pivot_index], arr[high] = arr[high], arr[pivot_index]
            pi = lomuto_partition_pivot(arr, low, high)
            quicksort_helper(arr, low, pi - 1)
            quicksort_helper(arr, pi + 1, high)
    quicksort_helper(arr, 0, len(arr) - 1)
    if reverse:
        arr.reverse()


In [41]:
# Testing Cell (Do NOT modify this cell)

#### Question 04 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
    def quicksort_numpy_arrays (alist, reverse = False):
```
that performs an ascending, inplace quicksort with a partition scheme of your choice on a list of NumPy arrays (`alist`) based on the sum of values in the array. The parameter `reverse` selects the direction of the sort order where `reverse == True` indicates a descending sort.

For example, give an input list of arrays like:
```python
[array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([0]),
 array([0, 1, 2]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4])]
```
the function will sort alist in place like:
```python
[array([0]),
 array([0, 1, 2]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8])]
```

In [42]:
### 4. quicksort_numpy_arrays
# Q: Sort list of numpy arrays by sum using quicksort logic.
# A: Use median quicksort logic with sum-based comparison.
def quicksort_numpy_arrays(alist, reverse=False):
    def quicksort(arr, low, high):
        if low < high:
            pivot_index = median_of_three_pivot(arr, low, high)
            arr[pivot_index], arr[high] = arr[high], arr[pivot_index]
            pi = lomuto_partition_pivot(arr, low, high)
            quicksort(arr, low, pi - 1)
            quicksort(arr, pi + 1, high)
    alist.sort(key=lambda x: np.sum(x))
    if reverse:
        alist.reverse()


In [43]:
# Testing Cell (Do NOT modify this cell)

#### Question 05 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def quicksort_alphabetical (arr, ignorecase = False):
 ```
that sorts a list of characters (single letter strings) in-place according to alphabetical order. When `ignorecase == True`, the case of letters in the list should be ignored.  When `ignorecase == False`, the sort should respect the case of the list according to Python's default behaviour: uppercase characters sort in preference to lowercase characters. 

In [44]:

### 5. quicksort_alphabetical
# Q: Sort strings alphabetically, optionally ignoring case.
# A: Use built-in sort with key and ignorecase toggle.
def quicksort_alphabetical(arr, ignorecase=False):
    if ignorecase:
        arr.sort(key=lambda x: x.lower())
    else:
        arr.sort()


In [45]:
# Testing Cell (Do NOT modify this cell)

#### Question 06 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```Python
def insertion_sort_string (un_list):
```
that sorts a list of strings in-place in descending order of their length using an insertion sort.

In [46]:


### 6. insertion_sort_string
# Q: Sort strings using insertion sort.
# A: Compare and insert elements in sorted portion.
def insertion_sort_string(un_list):
    for i in range(1, len(un_list)):
        key = un_list[i]
        j = i - 1
        while j >= 0 and un_list[j] > key:
            un_list[j + 1] = un_list[j]
            j -= 1
        un_list[j + 1] = key



In [47]:
# Testing Cell (Do NOT modify this cell)

#### Question 07 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def insertion_sort_dict_by_key (un_dict):
```
that performs an insertion sort that sorts a dict by ascending values in-place while retaining identical keys.

For example, given a dictionary:
```python
d = {
    1: 101,
    2: 2,
    8: -1,
}
```
would be sorted as:
```python
d = {
    1: -1,
    2: 2,
    8: 101,
}
```

In [48]:
### 7. insertion_sort_dict_by_key
# Q: Sort dictionary by keys using insertion sort.
# A: Build a sorted list of tuples using insertion sort.
def insertion_sort_dict_by_key(un_dict):
    items = list(un_dict.items())
    for i in range(1, len(items)):
        key = items[i]
        j = i - 1
        while j >= 0 and items[j][0] > key[0]:
            items[j + 1] = items[j]
            j -= 1
        items[j + 1] = key
    return dict(items)


In [49]:
# Testing Cell (Do NOT modify this cell)

#### Question 08 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def recursive_insertion_sort (arr, index, reverse):
```
that performs a recursive insertion sort in-place on a list of floats taking a `reverse` parameter to signal whether the floats are to be in ascending on descending order.

In [50]:

### 8. recursive_insertion_sort
# Q: Implement insertion sort recursively.
# A: Base case is index 1, insert current index into sorted left part.
def recursive_insertion_sort(arr, index, reverse=False):
    if index <= 0:
        return
    recursive_insertion_sort(arr, index - 1, reverse)
    key = arr[index]
    j = index - 1
    if reverse:
        while j >= 0 and arr[j] < key:
            arr[j + 1] = arr[j]
            j -= 1
    else:
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
    arr[j + 1] = key


In [51]:
# Testing Cell (Do NOT modify this cell)

#### Question 09 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_alpha_pivot(str_list, low, high):
```
that accepts a list of capitalised names, the index of the start and end of the partition in the list and returns a 'median of three' pivot value using a median partition scheme or `None` for a zero length input array. 

In calculating the pivot, the first letter of each string is given a weighting according to its index in `list(string.ascii_uppercase)` and the value returned is that index. 

Thus, in a list like:
```python
["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"]
```
in calculating the pivot for the whole of the list, we consider the values:
- 12 (the index of 'M' in string.ascii_uppercase), 
- 23 (the index of 'X' in string.ascii_uppercase), and 
- 17 (the index of 'R' in string.ascii_uppercase)   
returning `17` as our first pivot value.


In [52]:

### 9. median_alpha_pivot
# Q: Return index of median based on first character alphabetically.
# A: Use sorted tuple and return index.
def median_alpha_pivot(str_list, low, high):
    mid = (low + high) // 2
    trio = [(str_list[low], low), (str_list[mid], mid), (str_list[high], high)]
    trio.sort(key=lambda x: x[0][0].lower())
    return trio[1][1]



In [53]:
# Testing Cell (Do NOT modify this cell)

#### Question 10 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_quicksort_by_first_letter (str_list):
```   

that implements a **recursive** quicksort that sorts a list of capitalised names according to their first letter using the median partition scheme per the details expressed in Question 09. 

Thus, given a list like:
```python
["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui", "Pranav"]
```
when sorted in-place, the list is:
```python
['Biao', 'Fu', 'Majid', 'Pranav', 'Rui', 'Tashreque', 'Victoria', 'Xiefeng']
```

In [54]:
### 10. median_quicksort_by_first_letter
# Q: Sort using quicksort based on first letter.
# A: Use median_alpha_pivot for pivot.
def median_quicksort_by_first_letter(str_list):
    def quicksort(arr, low, high):
        if low < high:
            pivot_idx = median_alpha_pivot(arr, low, high)
            arr[pivot_idx], arr[high] = arr[high], arr[pivot_idx]
            pi = lomuto_partition_pivot(arr, low, high)
            quicksort(arr, low, pi - 1)
            quicksort(arr, pi + 1, high)
    quicksort(str_list, 0, len(str_list) - 1)



In [55]:
# Testing Cell (Do NOT modify this cell)

#### Question 11 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def insertion_sort_by_tuple_sum (ulist, reverse = False):
```
that sorts a list of numerical tuples in-place by the sum of all values in the tuple. The parameter `reverse` indicates an ascending or descending sort. 

In [56]:

### 11. insertion_sort_by_tuple_sum
# Q: Insertion sort on list of tuples by their sum.
# A: Compare sum of tuples and insert appropriately.
def insertion_sort_by_tuple_sum(ulist, reverse=False):
    for i in range(1, len(ulist)):
        key = ulist[i]
        j = i - 1
        if reverse:
            while j >= 0 and sum(ulist[j]) < sum(key):
                ulist[j + 1] = ulist[j]
                j -= 1
        else:
            while j >= 0 and sum(ulist[j]) > sum(key):
                ulist[j + 1] = ulist[j]
                j -= 1
        ulist[j + 1] = key

In [57]:
# Testing Cell (Do NOT modify this cell)