### Instructions:

- You can attempt any number of questions and in any order.  
  See the assignment page for a description of the hurdle requirement for this assessment.
- You may submit your practical for autograding as many times as you like to check on progress, however you will save time by checking and testing your own code before submitting.
- Develop and check your answers in the spaces provided.
- **Replace** the code `raise NotImplementedError()` with your solution to the question.
- Do **NOT** remove any variables other provided markings already provided in the answer spaces.
- Do **NOT** make any changes to this notebook outside of the spaces indicated.  
  (If you do this, the submission system might not accept your work)

### Submitting:

1. Before you turn this problem in, make sure everything runs as expected by resetting this notebook.    
   (You can do this from the menubar above by selecting `Kernel`&#8594;`Restart Kernel and Run All Cells...`)
1. Don't forget to save your notebook after this step.
1. Submit your .ipynb file to Gradescope via file upload or GitHub repository.
1. You can submit as many times as needed.



---

# <mark style="background: #801010; color: #ffffff;" >B2</mark> Topic 5: NumPy Arrays

#### Question 01 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(2 Points)

Create a python program that has a 1-D array with 5 elements. It should contain the numbers 0 to 4 in sequence. Assign this array to `output1`.

In [21]:
import numpy as np

# Creating a 1D NumPy array
output1 = np.array([0, 1, 2, 3, 4])

# Display the output
print(output1)


[0 1 2 3 4]


In [22]:
# Testing Cell (Do NOT modify this cell)

#### Question 02 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(2 Points)

Create a python program that contains a 2-D array with 6 elements (2 rows and 3 columns) that represents the following array. Assign this array to `output2`.

$$\begin{bmatrix} 0 & 1 & 2 \\ 3 & 4 & 5 \end{bmatrix}$$

In [23]:
import numpy as np

# Creating a 2D NumPy array (2 rows, 3 columns)
output2 = np.array([[0, 1, 2], [3, 4, 5]])

# Display the output
print(output2)


[[0 1 2]
 [3 4 5]]


In [24]:
# Testing Cell (Do NOT modify this cell)

#### Question 03 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(2 Points)
Create a python program that has a 2-D array with 6 elements (3 rows and 2 columns) that represents the following array. Assign this array to `output3`.

$$\begin{bmatrix} 0 & 1 \\ 2 & 3 \\ 4 & 5 \end{bmatrix}$$

In [25]:
import numpy as np

# Creating a 2D NumPy array (3 rows, 2 columns)
output3 = np.array([[0, 1], [2, 3], [4, 5]])

# Display the output
print(output3)


[[0 1]
 [2 3]
 [4 5]]


In [26]:
# Testing Cell (Do NOT modify this cell)

#### Question 04 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(2 Points)

Create a python program that has a 3-D array with 8 elements (2 rows and 2 columns, with a depth of 2) using the `zeros` function. Assign this array to `output4`.

In [27]:
import numpy as np

# Creating a 3D NumPy array (2 blocks, 2 rows, 2 columns)
output4 = np.zeros((2, 2, 2))

# Display the output
print(output4)


[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [28]:
# Testing Cell (Do NOT modify this cell)

#### Question 05 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(2 Points)

You are given a 2-D array of unknown size named `array5`. Create a Python function that finds the size of that array and returns the number of rows.

In [29]:
import numpy as np

def question05(array5):
    """
    This function takes a 2D NumPy array as input and returns the number of rows.
    """
    return array5.shape[0]

# Example usage
example_array = np.array([[1, 2], [3, 4], [5, 6]])  # 3 rows, 2 columns
print(question05(example_array))  # Output: 3


3


In [30]:
# Testing Cell (Do NOT modify this cell)

#### Question 06 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(2 Points)

Create a python program that performs the following calculation using universal functions. Assign the result to `output6`.

$$\begin{bmatrix} 0 & 1 \\ 2 & 3 \end{bmatrix} + \begin{bmatrix} 0 & 1 \\ 2 & 3 \end{bmatrix}$$

In [31]:
import numpy as np

# Defining the matrix
matrix = np.array([[0, 1], [2, 3]])

# Performing element-wise addition
output6 = matrix + matrix

# Display the output
print(output6)


[[0 2]
 [4 6]]


In [32]:
# Testing Cell (Do NOT modify this cell)

#### Question 07 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)
You are given two 2-D arrays of that are the same size (`array7_i` and `array7_ii`). Create a python program that multiplies the two arrays together using universal functions. Return a new array containing the result.

In [33]:
import numpy as np

def question07(a1, a2):
    """
    This function takes two 2D NumPy arrays of the same shape and returns
    an array where each element is the product of corresponding elements from a1 and a2.
    """
    return np.multiply(a1, a2)

# Example usage
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[2, 2], [2, 2]])

print(question07(array1, array2))


[[2 4]
 [6 8]]


In [34]:
# Testing Cell (Do NOT modify this cell)

#### Question 08 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)

Create a python program that performs the following calculation using universal functions. Assign the result to `output8`.

$$\begin{bmatrix} 0 & 1 \\ 2 & 3 \end{bmatrix} ** 3$$

In [35]:
import numpy as np

# Step 1: Define the given 2x2 matrix
matrix = np.array([[0, 1], 
                   [2, 3]])

# Step 2: Perform element-wise exponentiation (raise each element to the power of 3)
# - Using either np.power(matrix, 3) or matrix ** 3
output8 = matrix ** 3  

# Step 3: Print the result to verify correctness
print(output8)


[[ 0  1]
 [ 8 27]]


In [36]:
# Testing Cell (Do NOT modify this cell)

#### Question 09 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)

Create a python program that has a 1-D array with 100 elements. It should contain the numbers 0, 2, 4, 6, all the way to 198 in sequence. Assign this array to `output9`.

In [37]:
import numpy as np

# Step 1: Generate a sequence of numbers from 0 to 198 with step 2
output9 = np.arange(0, 200, 2)

# Step 2: Print the result to verify correctness
print(output9)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


In [38]:
# Testing Cell (Do NOT modify this cell)

#### Question 10 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)

Create a python program that has a 1-D array with 16 elements. It should contain the numbers 10, 20, 30, 40, all the way to 160 in sequence. Afterwards, change its shape using `reshape` to a 4-D array. Assign this reshaped array to `output10`.

***
<details>
  <summary><span style="color:blue">Click to see Hints</span></summary>
   In one of the provided examples, you saw how a 2-D 3-by-3 array. Use that as a basis for reshaping into a 4-D 2-by-2-by-2-by-2 array. 
</details>

In [39]:
import numpy as np

# Step 1: Generate a sequence from 10 to 160 with step 10
array_1d = np.arange(10, 170, 10)  # Creates [10, 20, 30, ..., 160]

# Step 2: Reshape the 1D array into a 4D array
output10 = array_1d.reshape(2, 2, 2, 2)  # Shape (2,2,2,2)

# Step 3: Print the reshaped array to verify correctness
print(output10)


[[[[ 10  20]
   [ 30  40]]

  [[ 50  60]
   [ 70  80]]]


 [[[ 90 100]
   [110 120]]

  [[130 140]
   [150 160]]]]


In [40]:
# Testing Cell (Do NOT modify this cell)

#### Question 11 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

One of the most common models in statistics (and by extention data science) is the normal distribution. In order to graph a normal distribution first the mean and standard deviation of the data must be found. NumPy has functions that allow us to analyse data and obtain these values.

You are given an array of unknown size and dimensions named `array11` that represents some data. Create a python program that finds the both the mean and standard deviation (rounded to 4 decimal points) of the data. Return the values in a dictionary of the following structure:
```python
question11 = {
  "mean": some_value,
  "standard_deviation": some_value
}
```

In [41]:
import numpy as np

def question11(array11):
    """
    This function calculates the mean and standard deviation of a given NumPy array.
    The results are rounded to 4 decimal places and returned as a dictionary.
    """
    # Step 1: Compute the mean of the array
    mean_value = round(np.mean(array11), 4)  # Rounding to 4 decimal places

    # Step 2: Compute the standard deviation of the array
    std_value = round(np.std(array11), 4)  # Rounding to 4 decimal places

    # Step 3: Store the results in a dictionary and return it
    return {
        "mean": mean_value,
        "standard_deviation": std_value
    }

# Example usage
example_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # Sample data
print(question11(example_array))  
# Expected Output: {'mean': 5.5, 'standard_deviation': 2.8723}


{'mean': 5.5, 'standard_deviation': 2.8723}


In [42]:
# Testing Cell (Do NOT modify this cell)

#### Question 12 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

You are given an 1-D array of unknown size named `array12`. Create a python program that finds both the first element and the minimum element in the array determined using a standard function. Return the values in a dictionary of the following structure:
```python
{
  "first": some_value,
  "smallest": some_value
}
```

In [43]:
import numpy as np

def question12(array12):
    """
    This function takes a 1D NumPy array and returns a dictionary containing:
    - The first element of the array.
    - The smallest element found using np.min().
    """
    # Step 1: Get the first element of the array
    first_element = array12[0]

    # Step 2: Find the smallest element in the array using NumPy's min() function
    smallest_element = np.min(array12)

    # Step 3: Store the results in a dictionary and return it
    return {
        "first": first_element,
        "smallest": smallest_element
    }

# Example usage
example_array = np.array([12, 4, 56, 1, 9, 7])  # Sample data
print(question12(example_array))  
# Expected Output: {'first': 12, 'smallest': 1}


{'first': 12, 'smallest': 1}


In [44]:
# Testing Cell (Do NOT modify this cell)

#### Question 13 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

You are given an 2-D array of unknown size named `array13`. Create a python program that finds the first row of data and the maximum number within that row.  Return the values in a dictionary of the following structure:
```python
question13 = {
  "first_row": some_value,
  "max_row_value": some_value
}
```

In [45]:
import numpy as np

def question13(array13):
    """
    This function takes a 2D NumPy array and returns a dictionary containing:
    - The first row as a list.
    - The maximum value in the first row.
    """
    # Step 1: Get the first row of the 2D array
    first_row = array13[0]  # Extracts the first row

    # Step 2: Find the maximum value in the first row
    max_row_value = np.max(first_row)  # Finds the highest value in the row

    # Step 3: Store the results in a dictionary and return it
    return {
        "first_row": first_row.tolist(),  # Convert NumPy array to a list for better readability
        "max_row_value": max_row_value
    }

# Example usage
example_array = np.array([[3, 8, 1, 7], [2, 5, 9, 6], [4, 10, 12, 0]])  # Sample data
print(question13(example_array))  
# Expected Output: {'first_row': [3, 8, 1, 7], 'max_row_value': 8}


{'first_row': [3, 8, 1, 7], 'max_row_value': 8}


In [46]:
# Testing Cell (Do NOT modify this cell)


#### Question 14 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

You are given an 1-D array of unknown size named `array14`. Create a python program that finds the first 6 entries within that row. Next, split that array into two arrays using the `split` function. Return the values in a dictionary of the following structure:
```python
question14 = {
  "array": first_6_entries,
  "part1": split_first_half,
  "part2": split_other_half
}
```

In [47]:
import numpy as np

def question14(array14):
    """
    This function extracts the first 6 elements of a given 1D NumPy array.
    It then splits this 6-element array into two equal halves using np.split().
    The function returns a dictionary containing:
    - The first 6 entries as a list.
    - The two split halves as lists.
    """
    # Step 1: Get the first 6 elements from the array
    first_6_entries = array14[:6]  # Extracts first 6 elements

    # Step 2: Split the 6-element array into two equal parts
    part1, part2 = np.split(first_6_entries, 2)  # Splits into 2 equal parts

    # Step 3: Store the results in a dictionary and return it
    return {
        "array": first_6_entries.tolist(),  # Convert NumPy array to list
        "part1": part1.tolist(),            # Convert first split part to list
        "part2": part2.tolist()             # Convert second split part to list
    }

# Example usage
example_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])  # Sample data
print(question14(example_array))  
# Expected Output: {'array': [10, 20, 30, 40, 50, 60], 'part1': [10, 20, 30], 'part2': [40, 50, 60]}


{'array': [10, 20, 30, 40, 50, 60], 'part1': [10, 20, 30], 'part2': [40, 50, 60]}


In [48]:
# Testing Cell (Do NOT modify this cell)

#### Question 15 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

You are given an 1-D array of 40 elements named `array15`. Create a Python program that finds every second element starting from index 4 and stopping before index 20. Return the result as an array.

In [49]:
import numpy as np

def question15(array15):
    """
    This function extracts every second element from a given 1D NumPy array.
    - Starts from index 4.
    - Stops before index 20.
    - Uses a step of 2.
    """
    # Step 1: Extract every second element from index 4 to index 20 (exclusive)
    result = array15[4:20:2]  # Start at 4, stop before 20, step by 2

    # Step 2: Return the resulting NumPy array
    return result

# Example usage
example_array = np.arange(40)  # Creates an array [0, 1, 2, ..., 39]
print(question15(example_array))  
# Expected Output: [4, 6, 8, 10, 12, 14, 16, 18]


[ 4  6  8 10 12 14 16 18]


In [50]:
# Testing Cell (Do NOT modify this cell)

#### Question 16 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

You are given 2 sorted 1-D arrays of 20 elements named `array16_i` and `array16_ii`. Create a python program that concatenates these two arrays by appending `array16_ii` to the end of `array16_i`. Afterwards, sort the new array.
Return both the unsorted concatenated array, and the sorted array in a dictionary of the following structure:
```python
question16 = {
  "concat": concatenated_array,
  "sorted": sorted_array
}
```

In [51]:
import numpy as np

def question16(array16_i, array16_ii):
    """
    This function takes two sorted 1D NumPy arrays, concatenates them,
    sorts the new array, and returns both versions in a dictionary.
    """
    # Step 1: Concatenate the two arrays
    concatenated_array = np.concatenate((array16_i, array16_ii))  # Appending array16_ii to array16_i

    # Step 2: Sort the concatenated array
    sorted_array = np.sort(concatenated_array)  # Sorting the combined array

    # Step 3: Store the results in a dictionary and return it
    return {
        "concat": concatenated_array,  # Unsorted concatenated array
        "sorted": sorted_array         # Sorted array
    }

# Example usage
array_a = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])
array_b = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

print(question16(array_a, array_b))


{'concat': array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28,
       30, 32, 34, 36, 38, 40]), 'sorted': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])}


In [52]:
# Testing Cell (Do NOT modify this cell)

#### Question 17 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(8 Points)

Create a python program that:

1. initializes two arrays using the `arange` function followed by the `reshape` functions.
   1. The first array should have 2 rows and 5 columns and contain the numbers 0, 1, 2, up to and including 9.
   2. The second array should  have 2 rows and 3 columns and contain the numbers 1, 3, 5, up to and including 11.
2. concatenates these two arrays by appending along the column axis (creating an array with 2 rows and 8 columns), then transposes the result (creating an array with 8 rows and 2 columns).

Assign the end result to `output17`.

In [53]:
import numpy as np

# Step 1: Create the first array (2 rows, 5 columns) with numbers from 0 to 9
# - np.arange(10) generates numbers from 0 to 9
# - .reshape(2, 5) converts it into a 2D array with 2 rows and 5 columns
array1 = np.arange(10).reshape(2, 5)

# Step 2: Create the second array (2 rows, 3 columns) with numbers 1, 3, 5, ..., 11
# - np.arange(1, 12, 2) generates numbers from 1 to 11 with a step of 2
# - .reshape(2, 3) converts it into a 2D array with 2 rows and 3 columns
array2 = np.arange(1, 12, 2).reshape(2, 3)

# Step 3: Concatenate the two arrays along the column axis (axis=1), creating a (2, 8) shape
# - np.concatenate((array1, array2), axis=1) appends array2 as additional columns to array1
concatenated_array = np.concatenate((array1, array2), axis=1)

# Step 4: Transpose the array to change the shape from (2, 8) → (8, 2)
# - .T transposes the rows and columns, converting (2,8) into (8,2)
output17 = concatenated_array.T

# Step 5: Print the final result to verify correctness
print(output17)


[[ 0  5]
 [ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 1  7]
 [ 3  9]
 [ 5 11]]


In [54]:
# Testing Cell (Do NOT modify this cell)

#### Question 18 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(8 Points)

Create a python program that:

1. initializes two arrays using the `arange` function followed by the `reshape` functions.
   1. The first array should have 4 rows and 2 columns and contain the numbers 0, 1, 2, up to 7.
   2. The second array should have 3 rows and 2 columns and contain the numbers 1, 3, 5, up to 11.
2. concatenates these two arrays by appending along the row axis.
3. afterwards, reshape the new array into a 1-D array and sort it in decending order.

Assign the end result to `output18`.

In [55]:
import numpy as np

# Step 1: Create the first array (4 rows, 2 columns) with numbers from 0 to 7
# - np.arange(8) generates numbers from 0 to 7
# - .reshape(4, 2) converts it into a 2D array with 4 rows and 2 columns
array1 = np.arange(8).reshape(4, 2)

# Step 2: Create the second array (3 rows, 2 columns) with numbers 1, 3, 5, ..., 11
# - np.arange(1, 12, 2) generates numbers from 1 to 11 with a step of 2
# - .reshape(3, 2) converts it into a 2D array with 3 rows and 2 columns
array2 = np.arange(1, 12, 2).reshape(3, 2)

# Step 3: Concatenate the two arrays along the row axis (axis=0), creating a (7, 2) shape
# - np.concatenate((array1, array2), axis=0) appends array2 as additional rows to array1
concatenated_array = np.concatenate((array1, array2), axis=0)

# Step 4: Reshape the array into a 1D array
# - .reshape(-1) flattens the array into a 1D array
flattened_array = concatenated_array.reshape(-1)

# Step 5: Sort the 1D array in descending order
# - np.sort() sorts in ascending order, so we use [::-1] to reverse it
output18 = np.sort(flattened_array)[::-1]

# Step 6: Print the final result to verify correctness
print(output18)


[11  9  7  7  6  5  5  4  3  3  2  1  1  0]


In [56]:
# Testing Cell (Do NOT modify this cell)

#### Question 19 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Create a python program that:

1. initializes two 2-D arrays as depicted below.
$$a1 = \begin{bmatrix} 70 & 51 & 89 \\ 42 & 15 & 8 \end{bmatrix}, a2 = \begin{bmatrix} 75 & 12 & 38 \\ 99 & 75 & 45 \end{bmatrix}$$
2. performs integer division, by dividing the elements of a1 by a2. Assign this result to `output19_i`.
3. sums the three arrays together. Assign this result to `output19_ii`, also assign a copy of the second row to `output19_iii`.


In [57]:
import numpy as np

# Step 1: Initialize the first 2D array (a1)
a1 = np.array([[70, 51, 89],
               [42, 15,  8]])

# Step 2: Initialize the second 2D array (a2)
a2 = np.array([[75, 12, 38],
               [99, 75, 45]])

# Step 3: Perform integer division (element-wise division with floor result)
# - Using // operator to perform element-wise integer division
output19_i = a1 // a2

# Step 4: Sum all three arrays together: a1 + a2 + output19_i
output19_ii = a1 + a2 + output19_i

# Step 5: Extract the second row of output19_ii
output19_iii = output19_ii[1].copy()  # Copy ensures a separate memory location

# Step 6: Print results to verify correctness
print("Integer Division Result (output19_i):\n", output19_i)
print("\nSum of Arrays (output19_ii):\n", output19_ii)
print("\nSecond Row Copy (output19_iii):\n", output19_iii)


Integer Division Result (output19_i):
 [[0 4 2]
 [0 0 0]]

Sum of Arrays (output19_ii):
 [[145  67 129]
 [141  90  53]]

Second Row Copy (output19_iii):
 [141  90  53]


In [58]:
# Testing Cell (Do NOT modify this cell)

#### Question 20 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Create a python program that:

1. initializes two 2-D arrays as depicted below.
$$a1 = \begin{bmatrix} 48 & 75 & 75 \\ 15 & 2 & 46 \end{bmatrix}, a2 = \begin{bmatrix} 78 & 15 & 87 \\ 0 & 61 & 9 \end{bmatrix}$$
2. multiplies the two arrays together, then slice the result to only assign the last column to `output20` (note: an n-row, 1-column array automatically converts into a 1-row, n-column array, leave your answer like this).


In [59]:
import numpy as np

# Step 1: Initialize the first 2D array (a1)
a1 = np.array([[48, 75, 75],
               [15,  2, 46]])

# Step 2: Initialize the second 2D array (a2)
a2 = np.array([[78, 15, 87],
               [ 0, 61,  9]])

# Step 3: Perform element-wise multiplication of the two arrays
# - This multiplies corresponding elements from a1 and a2
multiplication_result = a1 * a2

# Step 4: Extract only the last column of the multiplied array
# - Using [:, -1] to select all rows and only the last column
output20 = multiplication_result[:, -1]

# Step 5: Print the final result to verify correctness
print(output20)


[6525  414]


In [60]:
# Testing Cell (Do NOT modify this cell)